version: 0
language: en
settings:
  use-action-bar: false
  per-player-locale: true
  allow-redstone-on-locked: true
  default-modes: [ ]
database:
  type: sqlite
  path: ""
  hostname: ""
  database: ""
  username: ""
  password: ""
  prefix: ""
  properties: [ ]
lockpicking:
  enabled: false
  jam-duration: 60
  odds:
    "2":
      success: 0.50
      jam: 0.10
    "1":
      success: 0.40
      jam: 0.20
    "0":
      success: 0.33
      jam: 0.33
    "-1":
      success: 0.20
      jam: 0.40
    "-2":
      success: 0.10
      jam: 0.50
blocks:
  chest: { }
  trapped_chest: { }
  '#copper_chests': { }
  furnace: { }
  blast_furnace: { }
  smoker: { }
  dispenser: { }
  dropper: { }
  barrel: { }
  brewing_stand: { }
  composter: { }
  beacon: { }
  jukebox: { }
  note_block: { }
  lectern: { }
  chiseled_bookshelf: { }
  hopper: { }
  decorated_pot: { }
  crafter: { }
  '#shulker_boxes': { }
  '#anvil': { }
  '#cauldrons': { }
  '#wooden_shelves': { }
  ender_chest: { }
  '#standing_signs': { }
  '#wall_signs': { }
  '#all_hanging_signs': { }
  '#doors': { }
  '#trapdoors': { }
  '#fence_gates': { }
  '#banners': { }
entities:
  armor_stand: { }
  item_frame: { }
  glow_item_frame: { }
  painting: { }
  leash_knot: { }
  acacia_chest_boat: { }
  bamboo_chest_raft: { }
  birch_chest_boat: { }
  cherry_chest_boat: { }
  dark_oak_chest_boat: { }
  jungle_chest_boat: { }
  mangrove_chest_boat: { }
  oak_chest_boat: { }
  pale_oak_chest_boat: { }
  spruce_chest_boat: { }
  chest_minecart: { }
  furnace_minecart: { }
  hopper_minecart: { }
